baseURL = 'https://www.arunsr.in/'
title = "arunsrin's notes"
locale = 'en-us'
contentDir = 'home'
publishDir = 'public'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params]
  description = "The truth shall make ye fret."
  author = "Arun S"
  repo_name = "arunsrin"
  repo_url = "https://github.com/arunsrin/arunsrin"
  edit_url = "https://github.com/arunsrin/arunsrin/blob/master/home/"

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "github"

[[module.mounts]]
  source = 'home'
  target = 'content'
  files = ['**', '!static/**', '!css/**']

[[module.mounts]]
  source = 'home/static'
  target = 'static/static'

[[module.mounts]]
  source = 'home/css'
  target = 'static/css'
